'use strict';
var GAME_LEVELS = [
               ['                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                  xxx           ',
        '                                                   xx      xx    xx!xx          ',
        '                                    o o      xx                  x!!!x          ',
        '                                                                xx!xx           ',
        '                                   xxxxx                          xvx           ',
        '                                                                           xx   ',
        '                                         o o                                x   ',
        '                        o                                                    x  ',
        '                                         xxxxx                             o x  ',
        '                        o                                                    x  ',
        '     @                                                           xxxxx       x  ',
        '~\\----------\/~~~\\----------\/ xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx   ',
        'w(||||||||||)www(||||||||||) x   x                  x     x                     ',
        'w(||||||||||)www(||||||||||) x!!!x                  x!!!!!x                     '],
       ['                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                                ',
        '                                                                  xxx           ',
        '                                                   xx      xx    xx!xx          ',
        '                                    o o      xx                  x!!!x          ',
        '                                                                xx!xx           ',
        '                                   xxxxx                          xvx           ',
        '                                                                           xx   ',
        '  xx                                      o o                                x  ',
        '  x                     o                                                    x  ',
        '  x                                      xxxxx                             o x  ',
        '  x          xxxx       o                                                    x  ',
        '  x  @       x  x                                                xxxxx       x  ',
        '  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ',
        '                              x   x                  x     x                    ',
        '                              x!!!x                  x!!!!!x                    ',
        '                              x!!!x                  x!!!!!x                    ',
        '                              xxxxx                  xxxxxxx                    ',
        '                                                                                ',
        '                                                                                ']
];